# Generated by Django 2.2.3 on 2020-09-14 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectviewed',
            name='user_id',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
