# Generated by Django 3.1.1 on 2020-10-29 06:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('type', models.IntegerField(choices=[(1, '图片'), (2, '视频')], verbose_name='专辑类型')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
            ],
            options={
                'verbose_name': '专辑',
                'verbose_name_plural': '专辑',
            },
        ),
        migrations.CreateModel(
            name='AlbumTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='标签名')),
            ],
            options={
                'verbose_name': '专辑标签',
                'verbose_name_plural': '专辑标签',
            },
        ),
        migrations.CreateModel(
            name='AlbumPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_cover', models.BooleanField(default=False, verbose_name='是否封面')),
                ('remote_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='远程地址')),
                ('local_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='本地地址')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albumdownload.album')),
            ],
            options={
                'verbose_name': '专辑图片',
                'verbose_name_plural': '专辑图片',
            },
        ),
        migrations.CreateModel(
            name='AlbumDownloadPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_path', models.CharField(blank=True, max_length=200, null=True, verbose_name='下载地址')),
                ('password', models.CharField(blank=True, max_length=20, null=True, verbose_name='解压密码')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albumdownload.album')),
            ],
            options={
                'verbose_name': '专辑下载地址',
                'verbose_name_plural': '专辑下载地址',
            },
        ),
        migrations.AddField(
            model_name='album',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='albumdownload.albumtag'),
        ),
    ]
