# Generated by Django 3.1.1 on 2020-11-04 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albumdownload', '0002_albumpic_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumdownloadpath',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='提取码'),
        ),
    ]
