# Generated by Django 3.1.1 on 2020-10-16 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_userinformation_information_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='level_score',
            field=models.IntegerField(default=0, verbose_name='等级分'),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='score',
            field=models.IntegerField(default=0, verbose_name='积分'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_media_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='收藏媒体ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='收藏时间')),
                ('favorite_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='收藏用户')),
            ],
        ),
    ]
