# Generated by Django 3.0.5 on 2020-05-01 22:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200430_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['-created_at'], 'verbose_name': '媒体', 'verbose_name_plural': '媒体'},
        ),
        migrations.AddField(
            model_name='poster',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 1, 22, 2, 25, 715727, tzinfo=utc), verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='poster',
            name='poster_category',
            field=models.CharField(blank=True, max_length=10, verbose_name='poster类型'),
        ),
    ]
