# Generated by Django 3.0.5 on 2020-05-03 10:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200502_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='poster',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 10, 5, 36, 991552, tzinfo=utc), verbose_name='创建时间'),
        ),
    ]
