# Generated by Django 3.0.5 on 2020-05-03 10:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200503_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_number',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poster',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 10, 6, 15, 1361, tzinfo=utc), verbose_name='创建时间'),
        ),
    ]
