# Generated by Django 3.0.5 on 2020-05-05 09:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200503_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_number',
        ),
        migrations.AddField(
            model_name='poster',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='分类'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poster',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 5, 9, 27, 43, 812828, tzinfo=utc), verbose_name='创建时间'),
        ),
    ]
