# Generated by Django 2.2.3 on 2020-09-14 06:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200506_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media_id_str',
            field=models.CharField(max_length=36, verbose_name='媒体资源ID'),
        ),
        migrations.AlterField(
            model_name='media',
            name='post_id_str',
            field=models.CharField(max_length=36, verbose_name='推文id'),
        ),
        migrations.AlterField(
            model_name='media',
            name='user_id_str',
            field=models.CharField(max_length=36, verbose_name='发推用户id'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
    ]
