# Generated by Django 2.2.3 on 2020-09-15 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200913_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='insert_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
