# Generated by Django 2.2.3 on 2020-10-07 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_media_insert_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['-insert_timestamp'], 'verbose_name': '媒体', 'verbose_name_plural': '媒体'},
        ),
    ]
